'use client';
import {useEffect,useState} from 'react';
const QUESTION='원형보존지 관련 자료 모두 찾아줘';
const methods=[['A','브라우저 자동화','기본 노션 AI','브라우저에서 질문 입력 → 완료 대기 → 원문 수신'],['B','커스텀 에이전트 API','별도 커스텀 에이전트','공식 API로 질문 → 에이전트 완료 → 이벤트 수신'],['C','노션 → 루나 MCP','기본 노션 AI + A 실행기','브라우저로 질문 → 노션 AI → 루나 MCP 호출']];
const labels={not_run:'미실행',blocked:'진입 차단',passed:'통과',failed:'실패'};
export default function Page(){
 const [ready,setReady]=useState(null),[runs,setRuns]=useState([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/luna/lab/readiness',{cache:'no-store'}).then(r=>r.json()).then(setReady).catch(()=>setError('시험 서버 연결 상태를 읽지 못했습니다.'));},[]);
 async function run(method){setBusy(method);setError('');try{const started=performance.now();const response=await fetch('/api/luna/lab/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,question:QUESTION})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRuns(old=>[...old,{...data,client_roundtrip_ms:Math.round(performance.now()-started)}]);}catch(e){setError(e.message||'시험 요청 오류');}finally{setBusy('');}}
 function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({question:QUESTION,readiness:ready,runs},null,2)],{type:'application/json'}));a.download='luna-abc-test-results.json';a.click();URL.revokeObjectURL(a.href);}
 return <main><header><div className="brand">LUNA <span>CONNECTION LAB</span></div><span className="pill">운영과 분리된 시험 URL</span></header><section className="intro"><p className="eyebrow">NOTION · A / B / C</p><h1>질문부터 원문 수신까지,<br/>같은 요청으로 확인합니다.</h1><p>세 단계가 자동으로 이어진 경우에만 성공입니다. 준비 단계에서 막힌 요청에는 답변이나 검색 시간을 표시하지 않습니다.</p></section><p><a href="/lab-report.html">2026-10-03 확인 보고표 · 실제 노션 검색 미실행</a></p><section className="question"><label htmlFor="question">모든 방식에 동일한 질문 · 아폴론 Working 범위</label><textarea id="question" value={QUESTION} readOnly rows={2}/><p>운영 DB 연결 없음 · 기존 검색 결과 사용 없음 · 수동 답변 입력 없음</p></section><div className="methods">{methods.map(([id,title,type,description])=><section className="card" key={id}><div className="method"><b>{id}</b><span>{type}</span></div><h2>{title}</h2><p>{description}</p><ul>{ready?.methods?.[id]?.checks.map(([code,ok,label])=><li key={code}><span className={ok?'ok':'missing'}>{ok?'준비됨':'미준비'}</span>{label}</li>)}</ul><button disabled={!!busy||!ready} onClick={()=>run(id)}>{busy===id?'서버에서 확인 중…':`${id} 연결 시험`}</button></section>)}</div>{error&&<p role="alert">{error}</p>}<section className="results"><div className="result-header"><h2>실제 실행 기록</h2><button className="secondary" disabled={!runs.length} onClick={download}>기록 내려받기</button></div><p>진입 차단은 검색 실패와 다릅니다. ①이 통과하지 않으면 ②·③은 미실행으로 표시합니다.</p><div className="table-wrap"><table><thead><tr><th>방식</th><th>① 질문 전달</th><th>② 답변 완료</th><th>③ 원문 수신</th><th>검색 총시간</th><th>노션 답변</th></tr></thead><tbody>{runs.map(r=><tr key={r.request_id}><td>{r.method}</td>{r.stages.map(s=><td key={s.step}>{labels[s.status]||s.status}</td>)}<td>{r.total_ms===null?'미측정':`${r.total_ms} ms`}</td><td>{r.answer?'수신':'없음'}</td></tr>)}</tbody></table>{!runs.length&&<p className="empty">아직 실행 기록이 없습니다.</p>}</div>{runs.map(r=><details key={r.request_id} open><summary>{r.method} · {r.message}</summary><p>요청 ID: <code>{r.request_id}</code></p><p>시작: {r.started_at} · 연결 점검 {r.preflight_ms} ms <strong>— 검색 시간 아님</strong></p><ul>{r.missing?.map(m=><li key={m.code}>{m.label}: 미준비</li>)}</ul><p>질문 전송 여부: {r.notion_called?'전송됨':'전송되지 않음'} · 원문 수신: {r.answer?'있음':'없음'}</p><p>질문 해시: <code>{r.question_sha256}</code></p>{r.source_answer&&<div className="answer-pair"><section><h3>노션 원문</h3><pre>{r.source_answer}</pre></section><section><h3>루나 수신본</h3><pre>{r.answer}</pre></section></div>}</details>)}</section><footer>이 화면은 연결 가능성을 검증하기 위한 시험 환경입니다. 현재 결과는 브라우저 실행기·API 인증·검색 범위 준비 상태에 따라 결정됩니다.</footer></main>;
}
