'use client';
import {useEffect,useState} from 'react';
const QUESTION='원형보존지 관련 자료 모두 찾아줘';
export default function BrowserTrial(){
 const [job,setJob]=useState(null),[receipt,setReceipt]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[elapsed,setElapsed]=useState(0);
 useEffect(()=>{if(!job||result)return;const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-Date.parse(job.started_at))/1000)),1000);return()=>clearInterval(timer);},[job,result]);
 async function begin(){setBusy(true);setError('');try{const r=await fetch('/api/luna/lab/a/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:QUESTION})});const data=await r.json();if(!r.ok)throw Error(data.error);setJob(data);setResult(null);setReceipt('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function receive(){setBusy(true);setError('');try{const payload=JSON.parse(receipt);const r=await fetch('/api/luna/lab/a/receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job,receipt:payload})});const data=await r.json();if(!r.ok)throw Error(data.error);setResult(data);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main><header><div className="brand">LUNA <span>A · BROWSER TRIAL</span></div><span className="pill">운영과 분리된 시험</span></header><section className="intro"><p className="eyebrow">기본 노션 AI · 원문 연결 검증</p><h1>루나의 질문을 노션으로,<br/>노션의 원문을 루나로.</h1><p>이번 실행기는 ChatGPT의 로그인된 브라우저입니다. 한 실행 절차가 질문 전달과 원문 반환을 수행합니다. 상시 서버 자동화와 다중 사용자 운영은 이번 시험의 검증 범위가 아닙니다.</p></section><section className="question"><label htmlFor="a-question">시험 질문</label><textarea id="a-question" readOnly value={QUESTION} rows={2}/><p>기본 노션 AI · 아폴론 Working 출처 필터 · 외부 자료 제외</p><button disabled={busy||!!job} onClick={begin}>A 질문 보내기</button></section>{error&&<p role="alert">{error}</p>}{job&&<><section className="card"><h2>{result?'실행 기록':'브라우저 실행기 처리 중'}</h2><p>{result?`총 ${Math.round(result.total_ms/1000)}초`:`질문 요청 후 ${elapsed}초 경과`}</p><p>요청 ID: <code>{job.request_id}</code></p><p>실행 방식: 브라우저 실행기를 수동으로 시작한 1회 자동 전달 시험</p></section><details><summary>실행기가 읽는 요청</summary><pre data-testid="a-job" style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(job)}</pre></details><details open={!result}><summary>브라우저 실행기 반환 채널</summary><p>실행 코드가 노션의 질문·원문·출처를 읽어 전송하는 입력입니다. 사람이 작성한 답변은 시험 증거로 인정하지 않습니다.</p><label htmlFor="a-receipt">브라우저 실행 결과 JSON</label><textarea id="a-receipt" value={receipt} onChange={e=>setReceipt(e.target.value)} rows={5} style={{fontSize:12}}/><button disabled={busy||!receipt||!!result} onClick={receive}>자동 수신 결과 처리</button></details></>}{result&&<section className="results"><h2>루나에 도착한 노션 원문</h2><div className="table-wrap"><table><thead><tr><th>① 질문 전달</th><th>② 노션 완료 관찰</th><th>③ 원문 수신</th><th>노션 처리</th><th>서버 수신 처리</th></tr></thead><tbody><tr><td>{result.stages[0]}</td><td>{result.stages[1]}</td><td>{result.stages[2]}</td><td>{Math.round(result.generation_ms/1000)}초</td><td>{result.server_receive_ms} ms</td></tr></tbody></table></div><p>증거 유형: 브라우저 실행기의 화면 관찰. 기본 노션 AI의 공식 API 증명은 아닙니다.</p><p><a href={result.notion_url} target="_blank" rel="noreferrer">해당 노션 대화 열기</a></p><article data-testid="a-answer" style={{whiteSpace:'pre-wrap',background:'white',padding:24,borderRadius:12,lineHeight:1.85}}>{result.answer}</article><h3>원문에 포함된 출처 링크</h3><ol>{result.citations.map((c,i)=><li key={i}><a href={c.href} target="_blank" rel="noreferrer">{c.text||c.href}</a></li>)}</ol><details><summary>원문 일치·시간·범위 검증 정보</summary><pre data-testid="a-result" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({...result,answer:undefined},null,2)}</pre></details><p>본문은 요약·재작성 없이 반환됐습니다. Private 차단 보장, 사용자별 권한 격리, 재시도·동시 사용은 별도 검증이 필요합니다.</p></section>}<footer>B·C 시험 보류 · 운영 DB 연결 없음 · 회사 자료는 이 시험의 수신 응답에서만 표시하며 저장소에 커밋하지 않습니다.</footer></main>;
}
